export const COMPANY = {
  legalName: "HADEES TRADING (PTY) LTD",
  shortName: "Hadees Trading",
  tagline: "Your Complete Business Growth Partner",
  established: "2025",
  city: "Mahikeng",
  country: "South Africa",
  phone: "0837535798",
  phoneIntl: "+27837535798",
  email: "admin@hadeestrading.co.za",
  whatsapp: "27837535798",
  address: "Mahikeng, North West, South Africa",
} as const;

export const NAV = [
  { label: "Home", to: "/" },
  { label: "About", to: "/about" },
  { label: "Services", to: "/services" },
  { label: "Pricing", to: "/pricing" },
  { label: "Industries", to: "/industries" },
  { label: "Why Us", to: "/why-choose-us" },
  { label: "FAQ", to: "/faq" },
  { label: "Contact", to: "/contact" },
] as const;

/** Social presence — placeholders until the official handles go live. */
export const SOCIALS = [
  { key: "whatsapp", label: "WhatsApp Business", href: `https://wa.me/${COMPANY.whatsapp}` },
  { key: "facebook", label: "Facebook", href: "https://facebook.com/hadeestrading" },
  { key: "instagram", label: "Instagram", href: "https://instagram.com/hadeestrading" },
  { key: "linkedin", label: "LinkedIn", href: "https://linkedin.com/company/hadeestrading" },
  { key: "x", label: "X (Twitter)", href: "https://x.com/hadeestrading" },
  { key: "youtube", label: "YouTube", href: "https://youtube.com/@hadeestrading" },
  { key: "tiktok", label: "TikTok", href: "https://tiktok.com/@hadeestrading" },
  { key: "telegram", label: "Telegram", href: "https://t.me/hadeestrading" },
  { key: "discord", label: "Discord", href: "https://discord.gg/hadeestrading" },
] as const;

export type SocialKey = (typeof SOCIALS)[number]["key"];

export interface CatalogService {
  slug: string;
  category: string;
  name: string;
  price: string;
  amount: number;
  startingFrom?: boolean;
  desc: string;
  benefits?: readonly string[];
  includes?: readonly string[];
  cta: string;
  badge?: string;
  disclaimer?: string;
}

export interface ServiceCategory {
  slug: string;
  name: string;
  blurb: string;
  icon: string;
  services: readonly CatalogService[];
}

export const SERVICE_CATALOG: readonly ServiceCategory[] = [
  {
    slug: "business-registration",
    name: "Business Registration & Startup",
    blurb: "Get legally trading — CIPC registration, statutory documents and startup guidance.",
    icon: "building",
    services: [
      {
        slug: "company-registration",
        category: "Business Registration & Startup",
        name: "Pty Ltd Company Registration Package",
        price: "R1,500",
        amount: 1500,
        desc: "Full CIPC registration handled end-to-end, with every statutory document delivered digitally.",
        benefits: ["Trade legally within days", "Open a business bank account", "Qualify for tenders & contracts"],
        includes: [
          "Company Registration Assistance",
          "Name Reservation",
          "Company Documents",
          "Share Certificate",
          "Digital Delivery",
        ],
        cta: "Register My Company",
        badge: "Most Popular",
      },
      {
        slug: "name-reservation",
        category: "Business Registration & Startup",
        name: "Name Reservation Assistance",
        price: "R350",
        amount: 350,
        desc: "Secure your preferred company name with CIPC, including alternative name strategy.",
        benefits: ["Protect your brand name", "Up to 4 name options submitted"],
        includes: ["Name availability search", "CIPC name reservation filing", "Confirmation certificate"],
        cta: "Reserve My Name",
      },
      {
        slug: "company-amendment",
        category: "Business Registration & Startup",
        name: "Company Amendment Assistance",
        price: "R750",
        amount: 750,
        desc: "Update directors, addresses, financial year end or company name at CIPC.",
        benefits: ["Keep CIPC records accurate", "Avoid non-compliance penalties"],
        includes: ["Amendment forms prepared", "CIPC submission", "Updated disclosure certificate"],
        cta: "Amend My Company",
      },
      {
        slug: "share-certificate",
        category: "Business Registration & Startup",
        name: "Share Certificate Package",
        price: "R350",
        amount: 350,
        desc: "Legally drafted share certificates and share register for every member.",
        benefits: ["Proof of ownership for banks & funders", "Tender-ready documentation"],
        includes: ["Share certificates per shareholder", "Share register", "Digital delivery"],
        cta: "Order Now",
      },
      {
        slug: "starter-consultation",
        category: "Business Registration & Startup",
        name: "Business Starter Consultation",
        price: "R500",
        amount: 500,
        desc: "A structured session mapping your registration, compliance and growth roadmap.",
        benefits: ["Clear 90-day action plan", "Avoid costly wrong turns"],
        includes: ["60-minute consultation", "Written action plan", "Service & cost roadmap"],
        cta: "Book Consultation",
      },
    ],
  },
  {
    slug: "tax-compliance",
    name: "Tax & Business Compliance",
    blurb: "Stay compliant with SARS, CSD, UIF and the Compensation Fund all year round.",
    icon: "shield",
    services: [
      {
        slug: "tax-clearance",
        category: "Tax & Business Compliance",
        name: "Tax Clearance Assistance",
        price: "R350",
        amount: 350,
        desc: "SARS tax compliance status PIN obtained and verified for your business.",
        benefits: ["Required for most tenders", "Proof of good standing with SARS"],
        includes: ["eFiling profile check", "Compliance status application", "TCS PIN delivered"],
        cta: "Order Now",
      },
      {
        slug: "sars-efiling",
        category: "Tax & Business Compliance",
        name: "SARS eFiling Assistance",
        price: "R500",
        amount: 500,
        desc: "eFiling profile setup, registration and linking of your tax types.",
        benefits: ["Full control of your tax profile", "Faster submissions & refunds"],
        includes: ["eFiling registration", "Tax type linking", "Profile handover & training"],
        cta: "Get Assistance",
      },
      {
        slug: "bbbee",
        category: "Tax & Business Compliance",
        name: "B-BBEE Assistance",
        price: "R350",
        amount: 350,
        desc: "Affidavit-based B-BBEE certificate assistance for EME and QSE businesses.",
        benefits: ["Improve tender scoring", "Valid for 12 months"],
        includes: ["Affidavit preparation", "Commissioning guidance", "Digital certificate copy"],
        cta: "Order Now",
      },
      {
        slug: "csd-registration",
        category: "Tax & Business Compliance",
        name: "CSD Registration Assistance",
        price: "R750",
        amount: 750,
        desc: "Central Supplier Database registration so government can appoint you.",
        benefits: ["Mandatory for government work", "Supplier number issued"],
        includes: ["CSD profile creation", "Banking & tax verification", "Supplier report"],
        cta: "Register Now",
      },
      {
        slug: "uif-registration",
        category: "Tax & Business Compliance",
        name: "UIF Registration Assistance",
        price: "R750",
        amount: 750,
        desc: "Register as an employer with the Unemployment Insurance Fund.",
        benefits: ["Employ staff legally", "Required for Letter of Good Standing"],
        includes: ["UIF employer registration", "Reference number", "Submission guidance"],
        cta: "Register Now",
      },
      {
        slug: "coida",
        category: "Tax & Business Compliance",
        name: "COIDA Registration Package",
        price: "R3,500",
        amount: 3500,
        desc: "Workmen's compensation registration with the Compensation Fund, done properly.",
        benefits: ["Cover your workers", "Unlock Letter of Good Standing"],
        includes: ["COIDA registration", "Return of earnings guidance", "Registration certificate"],
        cta: "Register Now",
      },
      {
        slug: "letter-good-standing",
        category: "Tax & Business Compliance",
        name: "Letter of Good Standing Assistance",
        price: "R1,500",
        amount: 1500,
        desc: "Obtain your Compensation Fund Letter of Good Standing for site access and tenders.",
        benefits: ["Required on most construction sites", "Boosts tender compliance score"],
        includes: ["Return of earnings submission", "Account reconciliation", "Letter issued"],
        cta: "Order Now",
      },
    ],
  },
  {
    slug: "construction",
    name: "Construction & Contractor Services",
    blurb: "NHBRC, CIDB and health & safety compliance for contractors who want bigger projects.",
    icon: "hard-hat",
    services: [
      {
        slug: "nhbrc",
        category: "Construction & Contractor Services",
        name: "NHBRC Registration Assistance",
        price: "R4,500",
        amount: 4500,
        desc: "Home Builders Registration Council enrolment prepared and submitted for you.",
        benefits: ["Build residential homes legally", "Qualify for housing projects"],
        includes: ["Document preparation", "NHBRC application", "Assessment guidance", "Progress tracking"],
        cta: "Register Now",
      },
      {
        slug: "nhbrc-assistance",
        category: "Construction & Contractor Services",
        name: "NHBRC Renewal Assistance",
        price: "R500",
        amount: 500,
        desc: "Support with NHBRC annual renewals and supporting documentation.",
        benefits: ["Stay registered without lapses"],
        includes: ["Renewal submission", "Document checklist", "Confirmation"],
        cta: "Get Assistance",
      },
      {
        slug: "cidb-registration",
        category: "Construction & Contractor Services",
        name: "CIDB Registration Assistance",
        price: "R2,500",
        amount: 2500,
        desc: "Construction Industry Development Board registration at the right grading.",
        benefits: ["Bid on public construction tenders", "Recognised contractor grading"],
        includes: ["Grading assessment", "Document preparation", "CIDB submission", "Certificate delivery"],
        cta: "Register Now",
      },
      {
        slug: "cidb-upgrade",
        category: "Construction & Contractor Services",
        name: "CIDB Upgrade Assistance",
        price: "R3,500",
        amount: 3500,
        desc: "Move up a CIDB grade using your completed project and financial evidence.",
        benefits: ["Access higher-value tenders", "Stronger contractor profile"],
        includes: ["Track record compilation", "Financial capability pack", "Upgrade submission"],
        cta: "Upgrade My Grade",
      },
      {
        slug: "construction-compliance",
        category: "Construction & Contractor Services",
        name: "Construction Compliance Package",
        price: "R7,500",
        amount: 7500,
        desc: "The complete contractor compliance bundle — registrations and documentation in one project.",
        benefits: ["One team, one price", "Site- and tender-ready in weeks"],
        includes: ["CIDB assistance", "COIDA & Letter of Good Standing", "Health & safety file", "Compliance tracker"],
        cta: "Get Compliant",
        badge: "Best Value",
      },
      {
        slug: "health-safety-file",
        category: "Construction & Contractor Services",
        name: "Health & Safety File Preparation",
        price: "R2,500",
        amount: 2500,
        desc: "A site-ready OHS file compiled to client and legislative specification.",
        benefits: ["Pass site audits", "Avoid work stoppages"],
        includes: ["OHS policies & appointments", "Risk assessments", "Method statements", "Printable file pack"],
        cta: "Order Now",
      },
      {
        slug: "psira",
        category: "Construction & Contractor Services",
        name: "PSIRA Registration Assistance",
        price: "R1,500",
        amount: 1500,
        desc: "Document preparation, application guidance and coordination with accredited training providers.",
        benefits: ["Guided end-to-end process", "Progress tracking"],
        includes: ["Document preparation", "Application guidance", "Training provider coordination", "Progress tracking"],
        cta: "Apply Now",
        badge: "NEW",
        disclaimer:
          "HADEES TRADING (PTY) LTD is NOT a PSIRA-accredited training provider. We provide consultation and registration assistance only. Training is completed through accredited PSIRA training centres.",
      },
    ],
  },
  {
    slug: "tenders",
    name: "Tender & Business Development",
    blurb: "Win more work with tender-ready documents, profiles and professional business plans.",
    icon: "file",
    services: [
      {
        slug: "tender-review",
        category: "Tender & Business Development",
        name: "Tender Document Review",
        price: "R500",
        amount: 500,
        desc: "Line-by-line review of your tender pack before submission.",
        benefits: ["Avoid disqualification", "Fix gaps before the deadline"],
        includes: ["Compliance checklist", "Written findings report", "Corrective action list"],
        cta: "Order Now",
      },
      {
        slug: "tender-application",
        category: "Tender & Business Development",
        name: "Tender Application Assistance",
        price: "R2,500",
        amount: 2500,
        desc: "We complete and compile your tender application with you, start to finish.",
        benefits: ["Professional submission quality", "Deadline managed for you"],
        includes: ["Requirement analysis", "Form completion", "Document compilation", "Submission guidance"],
        cta: "Get Assistance",
      },
      {
        slug: "tender-package",
        category: "Tender & Business Development",
        name: "Tender Package Preparation",
        price: "R5,000",
        amount: 5000,
        desc: "A complete, reusable tender pack built around your business.",
        benefits: ["Submit faster on every tender", "Consistent professional presentation"],
        includes: ["Full compliance pack", "Company profile", "Capability statement", "Pricing schedule support"],
        cta: "Build My Pack",
      },
      {
        slug: "business-profile",
        category: "Tender & Business Development",
        name: "Business Profile Design",
        price: "R1,500",
        amount: 1500,
        desc: "A designed company profile that positions you as a serious contender.",
        benefits: ["Impress evaluators & clients", "Print and digital ready"],
        includes: ["Custom design", "Copywriting support", "PDF & print files"],
        cta: "Order Now",
      },
      {
        slug: "capability-statement",
        category: "Tender & Business Development",
        name: "Company Capability Statement",
        price: "R1,500",
        amount: 1500,
        desc: "A one-to-two page statement proving you can deliver the work.",
        benefits: ["Quick credibility with buyers", "Perfect for cold outreach"],
        includes: ["Capability copywriting", "Designed layout", "PDF delivery"],
        cta: "Order Now",
      },
      {
        slug: "business-plan",
        category: "Tender & Business Development",
        name: "Professional Business Plan",
        price: "R2,500",
        amount: 2500,
        desc: "A bank- and funder-ready business plan with financial projections.",
        benefits: ["Support funding applications", "Clarity on your model"],
        includes: ["Market & competitor analysis", "3-year financial projections", "Executive summary", "Editable file"],
        cta: "Order Now",
      },
      {
        slug: "company-portfolio",
        category: "Tender & Business Development",
        name: "Company Portfolio Design",
        price: "R2,500",
        amount: 2500,
        desc: "A designed portfolio showcasing your completed projects and track record.",
        benefits: ["Prove experience visually", "Win larger contracts"],
        includes: ["Project write-ups", "Photo layout & design", "Print & digital files"],
        cta: "Order Now",
      },
    ],
  },
  {
    slug: "website-design",
    name: "Website Design & Digital Solutions",
    blurb: "Fast, SEO-ready websites engineered to turn visitors into paying customers.",
    icon: "layout",
    services: [
      {
        slug: "website-starter",
        category: "Website Design & Digital Solutions",
        name: "Starter Website",
        price: "R1,500",
        amount: 1500,
        desc: "Launch a credible online presence in under two weeks.",
        benefits: ["Look established from day one", "Capture enquiries 24/7"],
        includes: [
          "Responsive Website",
          "Up to 5 Pages",
          "Contact Form",
          "WhatsApp Integration",
          "Mobile Friendly",
          "Basic SEO",
        ],
        cta: "Start Starter",
      },
      {
        slug: "website-business",
        category: "Website Design & Digital Solutions",
        name: "Business Website",
        price: "R2,500",
        amount: 2500,
        desc: "A custom-designed site built to convert visitors into qualified leads.",
        benefits: ["More enquiries per visitor", "Found on Google Maps"],
        includes: [
          "Professional Custom Design",
          "Up to 10 Pages",
          "Google Maps Integration",
          "Lead Capture Forms",
          "Basic SEO",
          "Mobile Optimised",
          "Contact Forms",
        ],
        cta: "Start Business",
        badge: "Most Popular",
      },
      {
        slug: "website-premium",
        category: "Website Design & Digital Solutions",
        name: "Premium Business Website",
        price: "R5,500",
        amount: 5500,
        desc: "A full digital storefront ready for payments, portals and automation.",
        benefits: ["Sell and get paid online", "Scales into a full platform"],
        includes: [
          "Premium Custom Design",
          "Unlimited Core Pages",
          "Client Portal Ready",
          "CRM Ready",
          "PayFast Ready",
          "Advanced SEO",
          "Performance Optimisation",
          "Blog",
          "Gallery",
          "Advanced Contact Forms",
        ],
        cta: "Start Premium",
        badge: "Enterprise",
      },
    ],
  },
  {
    slug: "branding",
    name: "Branding Services",
    blurb: "Identity systems that make a small business look like a serious operator.",
    icon: "sparkles",
    services: [
      {
        slug: "logo-design",
        category: "Branding Services",
        name: "Logo Design",
        price: "R1,000",
        amount: 1000,
        desc: "A distinctive, professionally crafted logo with full file formats.",
        benefits: ["Instant brand recognition", "Works in print & digital"],
        includes: ["3 concept directions", "2 revision rounds", "PNG, SVG & PDF files"],
        cta: "Order Now",
      },
      {
        slug: "letterhead-design",
        category: "Branding Services",
        name: "Letterhead Design",
        price: "R500",
        amount: 500,
        desc: "Branded letterhead for quotations, contracts and official correspondence.",
        benefits: ["Professional paperwork", "Editable by your team"],
        includes: ["Word & PDF templates", "Brand-matched layout"],
        cta: "Order Now",
      },
      {
        slug: "invoice-template",
        category: "Branding Services",
        name: "Invoice Template",
        price: "R400",
        amount: 400,
        desc: "Branded, tax-ready invoice and quotation templates.",
        benefits: ["Get paid faster", "SARS-friendly layout"],
        includes: ["Invoice template", "Quotation template", "Editable files"],
        cta: "Order Now",
      },
      {
        slug: "company-profile-design",
        category: "Branding Services",
        name: "Company Profile Design",
        price: "R2,500",
        amount: 2500,
        desc: "A premium multi-page company profile aligned to your brand.",
        benefits: ["Win trust in the first meeting", "Reusable in every tender"],
        includes: ["Design & layout", "Copy refinement", "Print & digital PDF"],
        cta: "Order Now",
      },
      {
        slug: "branding-package",
        category: "Branding Services",
        name: "Complete Branding Package",
        price: "R5,000",
        amount: 5000,
        desc: "Everything you need to launch a consistent, professional brand.",
        benefits: ["One coherent identity", "Ready for every channel"],
        includes: ["Logo suite", "Letterhead & invoice templates", "Company profile", "Brand guideline sheet"],
        cta: "Build My Brand",
        badge: "Best Value",
      },
    ],
  },
  {
    slug: "automation",
    name: "AI & Business Automation",
    blurb: "Systems that capture leads, follow up and run operations while you work.",
    icon: "bot",
    services: [
      {
        slug: "automation-starter",
        category: "AI & Business Automation",
        name: "Business Automation Starter",
        price: "R5,000",
        amount: 5000,
        startingFrom: true,
        desc: "Automate the repetitive admin that slows your business down.",
        benefits: ["Respond to leads instantly", "Fewer missed enquiries"],
        includes: ["WhatsApp Automation", "Lead Capture", "Email Automation", "Digital Forms"],
        cta: "Automate My Business",
      },
      {
        slug: "ai-business-os",
        category: "AI & Business Automation",
        name: "AI Business Operating System",
        price: "R15,000",
        amount: 15000,
        startingFrom: true,
        desc: "A complete operating system for your business: CRM, dashboards, workflows and an AI assistant.",
        benefits: ["One place to run everything", "Decisions backed by live data"],
        includes: ["CRM", "Business Dashboard", "Workflow Automation", "AI Assistant", "Reporting"],
        cta: "Book a Demo",
        badge: "Enterprise",
      },
    ],
  },
];

/**
 * Canonical priced-item registry (flattened catalog). Every entry is a
 * checkoutable service — `slug` is the id used by `/checkout?service=<slug>`,
 * `amount` is in ZAR.
 */
export const PRICED_SERVICES: readonly CatalogService[] = SERVICE_CATALOG.flatMap((c) => c.services);

export type PricedService = CatalogService;

export function findPricedService(slug: string): CatalogService | undefined {
  return PRICED_SERVICES.find((s) => s.slug === slug);
}

export function findCategory(slug: string): ServiceCategory | undefined {
  return SERVICE_CATALOG.find((c) => c.slug === slug);
}

export const FEATURED_PACKAGES = [
  {
    slug: "entrepreneur-starter",
    name: "Entrepreneur Starter",
    price: "R1,500",
    amount: 1500,
    audience: "For new businesses.",
    checkoutSlug: "company-registration",
    features: ["Pty Ltd registration", "Name reservation", "Share certificate", "Digital document pack"],
  },
  {
    slug: "business-compliance",
    name: "Business Compliance Package",
    price: "R3,500",
    amount: 3500,
    audience: "For growing companies.",
    checkoutSlug: "coida",
    features: ["COIDA registration", "Tax clearance", "B-BBEE affidavit", "CSD registration support"],
    badge: "Popular",
  },
  {
    slug: "contractor-growth",
    name: "Contractor Growth Package",
    price: "R7,500",
    amount: 7500,
    audience: "For contractors and construction businesses.",
    checkoutSlug: "construction-compliance",
    features: ["CIDB assistance", "Letter of Good Standing", "Health & safety file", "Tender-ready documents"],
  },
  {
    slug: "digital-growth",
    name: "Digital Growth Package",
    price: "R5,000",
    amount: 5000,
    audience: "For businesses wanting a complete digital presence.",
    checkoutSlug: "branding-package",
    features: ["Brand identity suite", "Business website", "WhatsApp & lead capture", "SEO foundations"],
  },
] as const;

export const WEBSITE_PACKAGES = SERVICE_CATALOG.find((c) => c.slug === "website-design")!.services.map((s) => ({
  slug: s.slug,
  name: s.name,
  price: s.price,
  amount: s.amount,
  tagline: s.desc,
  timeline:
    s.slug === "website-starter" ? "5 – 7 working days" : s.slug === "website-business" ? "7 – 10 working days" : "10 – 20 working days",
  features: s.includes ?? [],
  badge: s.badge ?? null,
  cta: s.cta,
}));

// Legacy alias retained for pages that still consume this shape.
export const REGISTRATION_PRICING = PRICED_SERVICES.filter(
  (s) => !s.slug.startsWith("website-") && s.category !== "Branding Services" && s.category !== "AI & Business Automation",
).map((s) => ({ name: s.name, price: s.price, desc: s.desc, slug: s.slug }));

export const SERVICES = [
  { slug: "website-design", name: "Website Design", desc: "High-performance, SEO-ready websites built to convert.", icon: "layout" },
  { slug: "business-registration", name: "Business Registration", desc: "CIPC, tax, COIDA, NHBRC, CIDB & CSD from one desk.", icon: "building" },
  { slug: "tender-assistance", name: "Tender Assistance", desc: "Find, prepare & submit government & corporate tenders.", icon: "file" },
  { slug: "compliance", name: "Compliance", desc: "Stay CIPC, SARS, COIDA, B-BBEE & POPIA compliant, all year.", icon: "shield" },
  { slug: "psira", name: "PSIRA Registration Assistance", desc: "Document prep & guidance for PSIRA registration. Assistance only.", icon: "shield" },
  { slug: "crm-systems", name: "CRM Systems", desc: "Own your pipeline with an enterprise-grade CRM.", icon: "users" },
  { slug: "business-automation", name: "Business Automation", desc: "Automate quotes, invoices, reminders & workflows.", icon: "zap" },
  { slug: "ai-automation", name: "AI Automation", desc: "Deploy AI agents that work while you sleep.", icon: "bot" },
  { slug: "enterprise-ai", name: "Enterprise AI", desc: "Document AI, tender AI, proposal AI, predictive analytics.", icon: "brain" },
  { slug: "branding", name: "Branding", desc: "Logos, letterheads & identity systems that command trust.", icon: "sparkles" },
  { slug: "digital-transformation", name: "Digital Transformation", desc: "Move paper processes into secure digital systems.", icon: "refresh" },
  { slug: "cloud-solutions", name: "Cloud Solutions", desc: "Cloud email, storage, backups & security.", icon: "cloud" },
  { slug: "it-consulting", name: "IT Consulting", desc: "Advisory for SMEs modernising their IT stack.", icon: "cpu" },
  { slug: "training", name: "Training", desc: "Team training on tools, compliance & AI adoption.", icon: "graduation" },
  { slug: "business-documentation", name: "Business Documentation", desc: "Policies, procedures, contracts & templates.", icon: "book" },
] as const;
