/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyChooseUsRouteImport } from './routes/why-choose-us'
import { Route as WebsiteDesignRouteImport } from './routes/website-design'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TendersRouteImport } from './routes/tenders'
import { Route as TenderSupportRouteImport } from './routes/tender-support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PsiraRegistrationRouteImport } from './routes/psira-registration'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PopiaRouteImport } from './routes/popia'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MobileAppRouteImport } from './routes/mobile-app'
import { Route as IvanOsRouteImport } from './routes/ivan-os'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EnterpriseAiRouteImport } from './routes/enterprise-ai'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConstructionServicesRouteImport } from './routes/construction-services'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as BusinessRegistrationRouteImport } from './routes/business-registration'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PaymentSuccessRouteImport } from './routes/payment.success'
import { Route as PaymentCancelledRouteImport } from './routes/payment.cancelled'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ApiPublicPayfastItnRouteImport } from './routes/api/public/payfast-itn'

const WhyChooseUsRoute = WhyChooseUsRouteImport.update({
  id: '/why-choose-us',
  path: '/why-choose-us',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDesignRoute = WebsiteDesignRouteImport.update({
  id: '/website-design',
  path: '/website-design',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TendersRoute = TendersRouteImport.update({
  id: '/tenders',
  path: '/tenders',
  getParentRoute: () => rootRouteImport,
} as any)
const TenderSupportRoute = TenderSupportRouteImport.update({
  id: '/tender-support',
  path: '/tender-support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PsiraRegistrationRoute = PsiraRegistrationRouteImport.update({
  id: '/psira-registration',
  path: '/psira-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PopiaRoute = PopiaRouteImport.update({
  id: '/popia',
  path: '/popia',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MobileAppRoute = MobileAppRouteImport.update({
  id: '/mobile-app',
  path: '/mobile-app',
  getParentRoute: () => rootRouteImport,
} as any)
const IvanOsRoute = IvanOsRouteImport.update({
  id: '/ivan-os',
  path: '/ivan-os',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseAiRoute = EnterpriseAiRouteImport.update({
  id: '/enterprise-ai',
  path: '/enterprise-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstructionServicesRoute = ConstructionServicesRouteImport.update({
  id: '/construction-services',
  path: '/construction-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRegistrationRoute = BusinessRegistrationRouteImport.update({
  id: '/business-registration',
  path: '/business-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentCancelledRoute = PaymentCancelledRouteImport.update({
  id: '/payment/cancelled',
  path: '/payment/cancelled',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicPayfastItnRoute = ApiPublicPayfastItnRouteImport.update({
  id: '/api/public/payfast-itn',
  path: '/api/public/payfast-itn',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business-registration': typeof BusinessRegistrationRoute
  '/checkout': typeof CheckoutRoute
  '/client-portal': typeof ClientPortalRoute
  '/compliance': typeof ComplianceRoute
  '/construction-services': typeof ConstructionServicesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/enterprise-ai': typeof EnterpriseAiRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-app': typeof MobileAppRoute
  '/packages': typeof PackagesRoute
  '/popia': typeof PopiaRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/psira-registration': typeof PsiraRegistrationRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tender-support': typeof TenderSupportRoute
  '/tenders': typeof TendersRoute
  '/terms': typeof TermsRoute
  '/website-design': typeof WebsiteDesignRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/payment/cancelled': typeof PaymentCancelledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/business-registration': typeof BusinessRegistrationRoute
  '/checkout': typeof CheckoutRoute
  '/client-portal': typeof ClientPortalRoute
  '/compliance': typeof ComplianceRoute
  '/construction-services': typeof ConstructionServicesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/enterprise-ai': typeof EnterpriseAiRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-app': typeof MobileAppRoute
  '/packages': typeof PackagesRoute
  '/popia': typeof PopiaRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/psira-registration': typeof PsiraRegistrationRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tender-support': typeof TenderSupportRoute
  '/tenders': typeof TendersRoute
  '/terms': typeof TermsRoute
  '/website-design': typeof WebsiteDesignRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/payment/cancelled': typeof PaymentCancelledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/business-registration': typeof BusinessRegistrationRoute
  '/checkout': typeof CheckoutRoute
  '/client-portal': typeof ClientPortalRoute
  '/compliance': typeof ComplianceRoute
  '/construction-services': typeof ConstructionServicesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/crm': typeof CrmRoute
  '/enterprise-ai': typeof EnterpriseAiRoute
  '/faq': typeof FaqRoute
  '/industries': typeof IndustriesRoute
  '/ivan-os': typeof IvanOsRoute
  '/mobile-app': typeof MobileAppRoute
  '/packages': typeof PackagesRoute
  '/popia': typeof PopiaRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/psira-registration': typeof PsiraRegistrationRoute
  '/refund': typeof RefundRoute
  '/services': typeof ServicesRoute
  '/shipping': typeof ShippingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tender-support': typeof TenderSupportRoute
  '/tenders': typeof TendersRoute
  '/terms': typeof TermsRoute
  '/website-design': typeof WebsiteDesignRoute
  '/why-choose-us': typeof WhyChooseUsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/payment/cancelled': typeof PaymentCancelledRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/payfast-itn': typeof ApiPublicPayfastItnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/business-registration'
    | '/checkout'
    | '/client-portal'
    | '/compliance'
    | '/construction-services'
    | '/contact'
    | '/cookies'
    | '/crm'
    | '/enterprise-ai'
    | '/faq'
    | '/industries'
    | '/ivan-os'
    | '/mobile-app'
    | '/packages'
    | '/popia'
    | '/pricing'
    | '/privacy'
    | '/psira-registration'
    | '/refund'
    | '/services'
    | '/shipping'
    | '/sitemap.xml'
    | '/tender-support'
    | '/tenders'
    | '/terms'
    | '/website-design'
    | '/why-choose-us'
    | '/admin/login'
    | '/admin/payments'
    | '/payment/cancelled'
    | '/payment/success'
    | '/admin/'
    | '/api/public/payfast-itn'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/business-registration'
    | '/checkout'
    | '/client-portal'
    | '/compliance'
    | '/construction-services'
    | '/contact'
    | '/cookies'
    | '/crm'
    | '/enterprise-ai'
    | '/faq'
    | '/industries'
    | '/ivan-os'
    | '/mobile-app'
    | '/packages'
    | '/popia'
    | '/pricing'
    | '/privacy'
    | '/psira-registration'
    | '/refund'
    | '/services'
    | '/shipping'
    | '/sitemap.xml'
    | '/tender-support'
    | '/tenders'
    | '/terms'
    | '/website-design'
    | '/why-choose-us'
    | '/admin/login'
    | '/admin/payments'
    | '/payment/cancelled'
    | '/payment/success'
    | '/admin'
    | '/api/public/payfast-itn'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/business-registration'
    | '/checkout'
    | '/client-portal'
    | '/compliance'
    | '/construction-services'
    | '/contact'
    | '/cookies'
    | '/crm'
    | '/enterprise-ai'
    | '/faq'
    | '/industries'
    | '/ivan-os'
    | '/mobile-app'
    | '/packages'
    | '/popia'
    | '/pricing'
    | '/privacy'
    | '/psira-registration'
    | '/refund'
    | '/services'
    | '/shipping'
    | '/sitemap.xml'
    | '/tender-support'
    | '/tenders'
    | '/terms'
    | '/website-design'
    | '/why-choose-us'
    | '/admin/login'
    | '/admin/payments'
    | '/payment/cancelled'
    | '/payment/success'
    | '/admin/'
    | '/api/public/payfast-itn'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BusinessRegistrationRoute: typeof BusinessRegistrationRoute
  CheckoutRoute: typeof CheckoutRoute
  ClientPortalRoute: typeof ClientPortalRoute
  ComplianceRoute: typeof ComplianceRoute
  ConstructionServicesRoute: typeof ConstructionServicesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CrmRoute: typeof CrmRoute
  EnterpriseAiRoute: typeof EnterpriseAiRoute
  FaqRoute: typeof FaqRoute
  IndustriesRoute: typeof IndustriesRoute
  IvanOsRoute: typeof IvanOsRoute
  MobileAppRoute: typeof MobileAppRoute
  PackagesRoute: typeof PackagesRoute
  PopiaRoute: typeof PopiaRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  PsiraRegistrationRoute: typeof PsiraRegistrationRoute
  RefundRoute: typeof RefundRoute
  ServicesRoute: typeof ServicesRoute
  ShippingRoute: typeof ShippingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TenderSupportRoute: typeof TenderSupportRoute
  TendersRoute: typeof TendersRoute
  TermsRoute: typeof TermsRoute
  WebsiteDesignRoute: typeof WebsiteDesignRoute
  WhyChooseUsRoute: typeof WhyChooseUsRoute
  PaymentCancelledRoute: typeof PaymentCancelledRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  ApiPublicPayfastItnRoute: typeof ApiPublicPayfastItnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-choose-us': {
      id: '/why-choose-us'
      path: '/why-choose-us'
      fullPath: '/why-choose-us'
      preLoaderRoute: typeof WhyChooseUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-design': {
      id: '/website-design'
      path: '/website-design'
      fullPath: '/website-design'
      preLoaderRoute: typeof WebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenders': {
      id: '/tenders'
      path: '/tenders'
      fullPath: '/tenders'
      preLoaderRoute: typeof TendersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tender-support': {
      id: '/tender-support'
      path: '/tender-support'
      fullPath: '/tender-support'
      preLoaderRoute: typeof TenderSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psira-registration': {
      id: '/psira-registration'
      path: '/psira-registration'
      fullPath: '/psira-registration'
      preLoaderRoute: typeof PsiraRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popia': {
      id: '/popia'
      path: '/popia'
      fullPath: '/popia'
      preLoaderRoute: typeof PopiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mobile-app': {
      id: '/mobile-app'
      path: '/mobile-app'
      fullPath: '/mobile-app'
      preLoaderRoute: typeof MobileAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ivan-os': {
      id: '/ivan-os'
      path: '/ivan-os'
      fullPath: '/ivan-os'
      preLoaderRoute: typeof IvanOsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise-ai': {
      id: '/enterprise-ai'
      path: '/enterprise-ai'
      fullPath: '/enterprise-ai'
      preLoaderRoute: typeof EnterpriseAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/construction-services': {
      id: '/construction-services'
      path: '/construction-services'
      fullPath: '/construction-services'
      preLoaderRoute: typeof ConstructionServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-registration': {
      id: '/business-registration'
      path: '/business-registration'
      fullPath: '/business-registration'
      preLoaderRoute: typeof BusinessRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/cancelled': {
      id: '/payment/cancelled'
      path: '/payment/cancelled'
      fullPath: '/payment/cancelled'
      preLoaderRoute: typeof PaymentCancelledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/payfast-itn': {
      id: '/api/public/payfast-itn'
      path: '/api/public/payfast-itn'
      fullPath: '/api/public/payfast-itn'
      preLoaderRoute: typeof ApiPublicPayfastItnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BusinessRegistrationRoute: BusinessRegistrationRoute,
  CheckoutRoute: CheckoutRoute,
  ClientPortalRoute: ClientPortalRoute,
  ComplianceRoute: ComplianceRoute,
  ConstructionServicesRoute: ConstructionServicesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CrmRoute: CrmRoute,
  EnterpriseAiRoute: EnterpriseAiRoute,
  FaqRoute: FaqRoute,
  IndustriesRoute: IndustriesRoute,
  IvanOsRoute: IvanOsRoute,
  MobileAppRoute: MobileAppRoute,
  PackagesRoute: PackagesRoute,
  PopiaRoute: PopiaRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  PsiraRegistrationRoute: PsiraRegistrationRoute,
  RefundRoute: RefundRoute,
  ServicesRoute: ServicesRoute,
  ShippingRoute: ShippingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TenderSupportRoute: TenderSupportRoute,
  TendersRoute: TendersRoute,
  TermsRoute: TermsRoute,
  WebsiteDesignRoute: WebsiteDesignRoute,
  WhyChooseUsRoute: WhyChooseUsRoute,
  PaymentCancelledRoute: PaymentCancelledRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  ApiPublicPayfastItnRoute: ApiPublicPayfastItnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
